name: '${project.name}'
version: '${project.version}'
main: '${project.groupId}.${project.artifactId}'
authors: [KIZAFOX]
description: '${project.description}'
website: '${project.url}'
api-version: '1.20'